name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU for multi-arch builds
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 🔧 Budujemy lokalny obraz do skanowania (tylko linux/amd64)
      - name: Build image for local scan
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          load: true
          platforms: linux/amd64
          tags: pogoda-app:latest

      - name: Save image to tar file (for scanning)
        run: docker save pogoda-app:latest -o image.tar

      - name: Scan image for vulnerabilities (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          input: image.tar
          severity: CRITICAL,HIGH
          format: table
          exit-code: 0

      # 🔧 Multi-arch push po skanowaniu
      - name: Push image to DockerHub and GHCR
        if: success()
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/pogoda-app:latest
            ghcr.io/${{ github.repository_owner }}/pogoda-app:latest
          cache-from: |
            type=registry,ref=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/pogoda-app-cache:latest
          cache-to: |
            type=registry,ref=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/pogoda-app-cache:latest,mode=max
